### ISSUE TITLE
gradle run

### ISSUE THREAD

**Issue by megalucio** [JavaPOSWorkingGroup/javapos-config-editor#1]
Would you please be able to provide some documentation on how to actually deploy/execute this? There is no run task in gradle so neither gradle run or ./gradlew run works. Thanks

**Comment by kuniss** [comment]
@megalucio, you do not need to build it by your self. It is already built. Just download it from here: https://bintray.com/javaposworkinggroup/maven/javapos-config-editor

In case, you want to know, how it is built in the cloud, read my blog article: http://blog.grammarcraft.de/2016/04/23/set-up-a-continuous-integration-process-in-the-cloud/
